version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - echo Build started on `date`
      - java -version
      - ./gradlew clean build
      - pwd
      - ls -l
      - cd ./build/libs
      - pwd
      - ls -l
      - aws s3 cp hello-world-gradle.jar s3://techops-eng-test-lambda-bucket-s3-2
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - deployspec.yml
    - ./build/libs/hello-world-gradle.jar
