version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11

  build:
    commands:
      - echo Build started on `date`
      - java -version
      - ./gradlew clean build
      - pwd
      - ls -l
      - aws s3 sync ./build/libs s3://$CODE_ARTIFACT_BUCKET --delete
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - deployspec.yml
    - ./build/libs/$CODE_ARTIFACT_NAME
