version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11

  build:
    commands:
      - echo Build started on `date`
      - java -version
      - ./gradlew clean build
      - pwd
      - ls -l
      - cd ./build/libs
      - pwd
      - ls -l
      - aws s3 sync ./ s3://techops-eng-dev-test-spa-bucket
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - deployspec.yml
    - ./build/libs/hello-world-gradle.jar
